version: '2'
services:
  phpstorm:
    build:
      context: .
    image: vrgfa/docker-x2go-phpstorm
    ports:
      - "2224:22"
    environment:
      - SSH_PASSWORD=phpstorm
    volumes:
      - /var/www/html:/var/www/html
